---
apiVersion: v1
kind: Service
metadata:
  name: kafka-kafdrop-service
  namespace: kafka
spec:
  ports:
    - protocol: "TCP"
      port: 9000
      name: server
  selector:
    app: kafka-kafdrop
  type: NodePort